### ISSUE TITLE
How long should SIC allow for a user to complete TOTP registration?

### ISSUE THREAD

**Issue by iamnvc** [sign-in-canada/Acceptance-Platform#99] opened 2023-01-31 16:02 UTC
When a user registers a TOTP authenticator app with their 1st factor GCKey or banking credential, they are doing so across three different systems, each with it's own session timeout and two of which are completely unaware of each other.

The applicable timeouts are:

20 minutes - the single sign-in timeout window of GKey an CBS. Once a user has correctly entered their password they can single-sign in to their Sign In Canada account for 20 minutes without having to re-enter their password
20 minutes - the maximum time that Sign In Canada waits for a user to sign-in or sign-up with the TOTP service
30 minutes - the maximum time a user can be idle before the TOTP service will time them out.

The 20 minute 1st factor timeout, added to the 30 minute TOTP idle timeout means that if a user signs in to their GCKey or banking credential and then abandons their computer, a malicious user has up to 50 minutes available to use that open session to register their own 2nd factor with the victim's first factor.

We need to decide if this is acceptable, or if SIC should enforce a limit on the time allowed to complete the end-to-end registration process and if so, what that time limit should be.

**Comment by wmoussa-gc** [comment] 2023-02-07 02:06
this is related to https://dev.azure.com/tbs-sct/Sign%20in%20Canada/_workitems/edit/9970

**Comment by wmoussa-gc** [comment] 2023-02-07 02:36
NIST 800-63 sec 7.2 recommends max 30 minutes of inactivity before re-authenticating. Can we make sure we track those events in our metrics? i.e. re-authentication kicks in after x minutes of inactivity.

**Comment by harrdou** [comment] 2023-02-07 14:34
We already have telemetry showing many people need more than 20 minutes (the current timeout). Reducing that would negatively impact the usability of ATIP online, forcing users to re-start registration from scratch every time they can't finish in time.

The issue is the user is not inactive, they are active at an externally-managed system where we have no visibility (where a 30 min inactivity timeout is in place).

**Comment by harrdou** [comment] 2023-02-07 14:39
Asking SSC to reduce the idle timeout on their service would bring it into alignment with the NIST guideline, but this decision here relates to total end-to-end time across 3 systems, not inactive time at any one of them.

**Comment by wmoussa-gc** [comment] 2023-02-23 16:43
closing duplicate of https://github.com/sign-in-canada/Acceptance-Platform/issues/108

**Closed by wmoussa-gc** 2023-02-23 16:43 UTC
